POST http://0.0.0.0:8080/query
Content-Type: application/json

{
  "collection": "customer",
  "query": {
    "fields": {
      "custkey": {
        "type": "column",
        "column": "custkey",
        "fields": null
      }
    },
    "limit": 3
  }
}